### ISSUE TITLE
Generator does not preserve string break for properties

### ISSUE THREAD

**Issue by erem2k** [overfl0/Armaclass#4]
`armaclass.arma_generator.ArmaGenerator` seems to fail to preserve broken up SQF property strings (`var="a" \n "b" \n "c";`) treating them as regular strings instead, which causes the discrepancy between original and armaclass-serialized SQF definitions that contain broken up strings.

**Example:**
Given following SQF 
```
class Item0 {
    init="[this, ""Platoon""] call FP_fnc_setVehicleName;" \n "this addMagazineCargoGlobal [""1Rnd_HE_Grenade_shell"", 10];";
};
```

`armaclass.Parser` would deserialize it as the following python dict - so far so good
```
{'Item0': {'init': '[this, "Platoon"] call FP_fnc_setVehicleName;\nthis addMagazineCargoGlobal ["1Rnd_HE_Grenade_shell", 10];'}}
```

However when attempting to serialize it back into SQF again, generator would output this:
```
class Item0
{
    init="[this, ""Platoon""] call FP_fnc_setVehicleName;
    this addMagazineCargoGlobal [""1Rnd_HE_Grenade_shell"", 10];";
};
```

The newline break would be inserted into the string property directly, and we'll lose all previously defined lines in the property; among other things this would also break the markup for sqms.
Solution to this would be to extend the `armaclass.arma_generator.ArmaGenerator.generate_string` to properly tokenize the parsed string by newlines and then serializing it.

**Comment by erem2k** [comment]
For missions specifically this would be caused by having multiline inits for objects and trigger expressions

**Comment by overfl0** [comment]
Merged! Thanks 👍
